version: "3"

services:
  quiz-ed-next:
    container_name: quiz-ed-next
    build:
      context: ./quiz-ed-next
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3001:3000
